"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"Indicates what fields are available at the top level of a query operation."
type Shipment {
  shipment_id: ID!
  order_id: Int!
  tracking_number: String!
  status: String!
  carrier: String!
  estimated_delivery: DateTime
  actual_delivery: DateTime
  shipping_address: String!
  created_at: DateTime
  updated_at: DateTime
}

type Query {
  shipments: [Shipment!]! @all
  shipment(id: ID!): Shipment @find
}