events {}

http {
    upstream order_service {
        server order_service:3000;
    }
    upstream product_service {
        server product_service:3000;
    }
    upstream user_service {
        server user_service:3000;
    }

    server {
        listen 80;

        location /orders/ {
            proxy_pass http://order_service/;
        }

        location /products/ {
            proxy_pass http://product_service/;
        }

        location /users/ {
            proxy_pass http://user_service/;
        }
    }
}